# Generated by Django 4.1.3 on 2022-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('date_v', models.JSONField()),
                ('date_k', models.JSONField()),
                ('date_w', models.JSONField()),
            ],
        ),
    ]
